### ISSUE TITLE
Assets automatic download/resolvement?

### ISSUE THREAD

**Issue by SolAstri** [Myriad-Dreamin/typst.ts#1]
I've cloned your repo and compilation fails because of missing fonts. Do you plan to publish them on GitHub or use them somehow otherwise?

**Comment by Myriad-Dreamin** [comment]
@SolAstri I have made a document about [Download Font Assets](https://github.com/Myriad-Dreamin/typst.ts/blob/main/docs/download-font-assets.md).

Feel free to ask me if you have any questions.
