### ISSUE TITLE
Typst.ts for Vue3

### ISSUE THREAD

**Issue by Myriad-Dreamin** [Myriad-Dreamin/typst.ts#3]
working
+ [x] Init Vue3 Library
+ [x] import `@myriaddreamin/typst.ts`
+ [x] A customized demo for typst.vue3
+ [x] Publish to npm

**Comment by quank123wip** [comment]
Interested taking this up in July, is that OK or you want to make it earlier? 😄

**Comment by Myriad-Dreamin** [comment]
> Interested taking this up in July, is that OK or you want to make it earlier? 😄

We are actively work on "next-generation" renderer, and I will update all packages then. But I'm not sure whether we will finish them in recent months. Feel free to do it as your like!
