### ISSUE TITLE
Dynamic layout comilation fails `failed to decompress package`

### ISSUE THREAD

**Issue by JnsJensen** [Myriad-Dreamin/typst.ts#355]
I attempt to use the `--dynamic-layout` compilation option, however, I receive the following error:

```bash
$ typst-ts-cli compile -e main.typ --dynamic-layout                                                                                                                                                                        
error: failed to decompress package (failed to iterate over archive)
```

I attempted to use the `--trace` option to get an idea of what was happened, however, I do not think I was able to use it correctly as it kept telling me that `error: init trace failed: invalid digit found in string`

**Comment by Myriad-Dreamin** [comment]
Hi, you should setup the [variables](https://github.com/Myriad-Dreamin/typst.ts/tree/main/contrib/templates/variables) package locally for dynamic layout. And I've write some comment for you just now.

For the trace option, how did you use it? I tried `--trace=verbosity=3`, it worked for me.

**Comment by Myriad-Dreamin** [comment]
Added documentation here: https://myriad-dreamin.github.io/typst.ts/cookery/guide/compiler/ts-cli.html
