### ISSUE TITLE
incorrect exports specified in @myriaddreamin/typst.react package.json

### ISSUE THREAD

**Issue by sinchang** [Myriad-Dreamin/typst.ts#378]
version: @myriaddreamin/typst.react@0.4.0-rc8

more info: https://publint.dev/@myriaddreamin/typst.react@0.4.0-rc8

**Comment by Myriad-Dreamin** [comment]
Thank you for information, I was always annoy with making the new `exports` field correct (compare with `main`, `types`, and `module` field). I will check it and fix errors and warnings about them.

**Comment by Myriad-Dreamin** [comment]
some warnings are left on latest version but we could leave them for more design
