### ISSUE TITLE
Implement a remark plugin to embed typst in markdown documents

### ISSUE THREAD

**Issue by quank123wip** [Myriad-Dreamin/typst.ts#505]
Since several markdown renders supports using MathJax or KaTeX to render math contents, it's a good idea to make typst an alternative option.

And, of course, markdown-it is a good option too, but I'm not going to work on it.😮‍💨

I'm going to work on this months later, just regard this issue as a reminder here. Of course, volunteers are welcomed.

**Comment by Myriad-Dreamin** [comment]
You can check it https://github.com/Myriad-Dreamin/typst.ts/tree/main/projects/rehype-typst, which renders typst math block in HTML.

**Comment by Enter-tainer** [comment]
combine remark-math and rehype-typst you can already do that. Demo here https://github.com/Myriad-Dreamin/typst.ts/blob/main/projects/rehype-typst/test.js#L28

**Comment by Loosetooth** [comment]
I was going to try the `rehype-typst` package, but I can't install it.

https://github.com/Myriad-Dreamin/typst.ts/blob/main/projects/rehype-typst/README.md?plain=1#L37

Is it published on npm?

I was also trying to install it directly from the git repo, but I couldn't immediately figure out how to install a package from a subfolder of a git repo.

**Comment by Myriad-Dreamin** [comment]
> I was going to try the `rehype-typst` package, but I can't install it.
> 
> https://github.com/Myriad-Dreamin/typst.ts/blob/main/projects/rehype-typst/README.md?plain=1#L37
> 
> Is it published on npm?
> 
> I was also trying to install it directly from the git repo, but I couldn't immediately figure out how to install a package from a subfolder of a git repo.
> 
> EDIT: I used this app to install `rehype-typst` from a subfolder of this git repo: https://gitpkg.vercel.app/about Add the following url in the app: https://github.com/Myriad-Dreamin/typst.ts/tree/main/projects/rehype-typst

It's my missing that it is not published. I'll test it again and publish it then in this week.

**Comment by quank123wip** [comment]
Working on a markdown preset now, I'm intereseted in supporting both LaTeX and Typst, maybe we can make a api to specific a mode let rehype-typst use alternative patterns like ```typst``` or ```math-typst``` and give typst a special token in markdown.

**Comment by Myriad-Dreamin** [comment]
I think `rehype-typst` already satisfies the requirement of this issue. Feel free to open new issues and focus new problem when using `rehype-typst`.
