### ISSUE TITLE
Loading custom fonts server-side (non-cli)

### ISSUE THREAD

**Issue by lhjt** [Myriad-Dreamin/typst.ts#514]
Hello - thanks for this library! It has worked really well so far, and I am keen to see further developments. My apologies if this feature already exists; I am just not sure how to do it yet.

**Is your feature request related to a problem? Please describe.**

At the moment, I'm generating PDFs using the All-in-one (Simplified) JavaScript Library (using the `$typst` import) in my NodeJS server. However, I cannot currently figure out a way to load in a custom font (I have the font file).

**Describe the solution you'd like**

Some method that I can call to set the path to check for fonts (and map them in), or any other method that you suggest. I have no qualms if I have to use an alternative method through the library (as in not using the simplified library - I just happened to be using it because it just works™)

**Describe alternatives you've considered**

I've read through the [documentation](https://myriad-dreamin.github.io/typst.ts/cookery/guide/all-in-one.html), but it looks like the font-related pages are still under development.

**Additional context**

I am currently creating the document via `$typst.pdf({ mainContent })`, and I have managed to get images to appear in my pdf successfully via mapShadow.

Thanks in advance!

**Comment by lhjt** [comment]
Thanks so much for your reply! I have managed to use the `preloadRemoteFonts` method you've mentioned here to get my custom TTF font in and rendered.

I did run into an issue where I was unable to get other font variants (such as bold versions of my ttf fonts) to load, but I think that's because I didn't refer to the correct TTF name.

Would you like me to close this issue or keep it open until typst.node/your other solution is merged in? Keen to see the native performance with typst.node and some documentation on how to use it. Thanks again!

**Comment by Myriad-Dreamin** [comment]
thank you for your patience 😊. You can freely close it or keep opening as you wish.

**Comment by Myriad-Dreamin** [comment]
closing in flavor of having node compiler. Please see [templates/compiler-node](https://github.com/Myriad-Dreamin/typst.ts/tree/main/templates/compiler-node) for use.
