### ISSUE TITLE
Document rehype-typst

### ISSUE THREAD

**Issue by Loosetooth** [Myriad-Dreamin/typst.ts#519]
I discovered the existence of the `rehype-typst` package by accident because of #505 

I tried it out using Next.js + MDX + rehype-typst in my [example project here](https://github.com/Loosetooth/next-rehype-typst-mdx) and the basic functions seem to work fine!

Perhaps it would be a good idea to add information about `rehype-typst` to the README, so that others can find it more easily.
Right now it's really hidden.

Let me know if you need any help.

**Comment by Myriad-Dreamin** [comment]
Is the readme enough? Please see [@myriaddreamin/rehype-typst](https://www.npmjs.com/package/@myriaddreamin/rehype-typst).

**Comment by Myriad-Dreamin** [comment]
Oh, at least it should be added to the root of readme.

**Comment by Loosetooth** [comment]
Looks good. I added some links to the readme in #560.
