### ISSUE TITLE
Demo page not working: function import requires a callable

### ISSUE THREAD

**Issue by ExpandOcean** [Myriad-Dreamin/typst.ts#547]
Hello, thanks for this awesome project!

I am working on a simple demo but the wasm loading always failed. 
Even the demo page failed. Does a mismatch between js and wasm cause this?

LinkError: WebAssembly.instantiate(): Import #3 "wbg" "__wbg_set_f975102236d3c502": function import requires a callable
![image](https://github.com/Myriad-Dreamin/typst.ts/assets/4313075/cab37507-2a44-4d6c-ba9e-cab2df5183b2)

**Comment by Myriad-Dreamin** [comment]
Seems that npm doesn't cache it correctly (since I published it recently). You can try to add a version after the package names to fix the version of these packages:
```html

    <script
      type="module"
      src="https://cdn.jsdelivr.net/npm/@myriaddreamin/typst.ts@0.5.0-rc5/dist/esm/contrib/all-in-one-lite.bundle.js"
      id="typst"
    ></script>
     ... long source code then ...
    <script>
     ... long source code then ...
      document.getElementById('typst').addEventListener('load', function () {
        $typst.setCompilerInitOptions({
          getModule: () =>
            'https://cdn.jsdelivr.net/npm/@myriaddreamin/typst-ts-web-compiler@0.5.0-rc5/pkg/typst_ts_web_compiler_bg.wasm',
        });
        $typst.setRendererInitOptions({
          getModule: () =>
            'https://cdn.jsdelivr.net/npm/@myriaddreamin/typst-ts-renderer@0.5.0-rc5/pkg/typst_ts_renderer_bg.wasm',
        });
    </script>

```
