### ISSUE TITLE
Issue initializing `highlighter-typst`

### ISSUE THREAD

**Issue by Aeolun** [Myriad-Dreamin/typst.ts#561]
**Describe the bug** && **To Reproduce**

Given the following code:

```typescript
import hljs from "highlight.js";
import { hljsTypst, initHljs } from "@myriaddreamin/highlighter-typst";

initHljs()
  .then((parser) => {
    console.log("parser initialized");
    hljs.registerLanguage(
      "typst",
      hljsTypst({
        // TypstHljsOptions
        codeBlockDefaultLanguage: "typst",
      }),
    );
  })
  .catch((error) => {
    console.error("parser failed to initialize", error);
  });
```

I get a `TypeError: undefined is not an object (evaluating 'wasm.__wbindgen_add_to_stack_pointer')` error in my browser console. I assume this has something to do with loading the typst parser, but I'm not sure if it's a bug, or something on my side that I'm doing wrong.

All the examples assume I'm importing from a CDN and pulling from `window`.

**Expected behavior**
I expect the typst parser to initialize without any errors when calling the `initHljs` function.

**Desktop (please complete the following information):**
 - OS: POP OS 22.04 LTS
 - Browser: Firefox 126.0
 - Version: 126.0

**Package/Software version (using command `typst-ts-cli --VV full` and paste down the output):**
I suspect this doesn't apply, but if it does I'll be happy to provide the information.

The version of highlighter-typst I'm using is `"@myriaddreamin/highlighter-typst": "0.4.1-rc1",`

**Additional context**
If the issue is on my side feel free to ignore this, but I'd appreciate any pointers towards resolving the issue.

**Comment by Myriad-Dreamin** [comment]
There is an [example HTML](https://github.com/Myriad-Dreamin/typst.ts/blob/main/projects/highlighter/index.html) to examine whether it is working in your firefox before checking your code.

According to index.html, you might miss a vital step: initializing the typst parser module. The functional ways to initialize it are given in the [projects/highlighter/src/contrib/hljs](https://github.com/Myriad-Dreamin/typst.ts/tree/476fc96efaa82f5212bee27b5f20f38a7f68927a/projects/highlighter/src/contrib/hljs).

```js
window.$typst$parserModule = typstInit(parserModule).then(() => initHljs());
                          // ^^^^^^^^^^^^^^^^^^^^^^^ what you are missing
```
