### ISSUE TITLE
Demo Doesn't work

### ISSUE THREAD

**Issue by Flinner** [Myriad-Dreamin/typst.ts#611]
**Describe the bug**
https://myriad-dreamin.github.io/typst.ts/preview.html this doesn't work

**To Reproduce**
Steps to reproduce the behavior (Library test):
1. Go to https://myriad-dreamin.github.io/typst.ts/preview.html
2. Click "Export to PDF"

**Console Output**
```
Uncaught (in promise) LinkError: import object field '__wbg_call_3bfa248576352471' is not a Function
Uncaught (in promise) LinkError: import object field '__wbg_iterator_695d699a44d6234c' is not a Function
```

**Comment by Myriad-Dreamin** [comment]
I have fixed it in https://github.com/Myriad-Dreamin/typst.ts/pull/623 and purged caches on jsdelivr. Now it works on my computer. Please invalid your browser caches and check it again.

**Comment by Flinner** [comment]
Works :1st_place_medal:  thanks
