### ISSUE TITLE
RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by imkonsowa** [Myriad-Dreamin/typst.ts#612]
**Describe the bug**

Compiling typst:

`const svg = await $typst.svg({mainContent: typstContent});`

Causing `memory access out of bounds` after re-installing node_modules today, It used to work like 3 days ago.

**To Reproduce**

Clone and run: https://github.com/imkonsowa/typst-resume-builder.git using `npm run dev`

**Expected behavior**
To render svg 

**Desktop:**
 - OS: Macbook M1 Pro
 - Browser: chrome
 - Version: latest

**Comment by Myriad-Dreamin** [comment]
You didn't align the version to use: https://github.com/imkonsowa/typst-resume-builder/blob/d4248e14ce73b005ae89b0dd1483796ed0e9d289/package-lock.json#L961

Some of them is `0.5.0` but the `@myriaddreamin/typst.ts` is `0.5.0-rc5`

**Comment by imkonsowa** [comment]
@Myriad-Dreamin Thanks! Fixing all versions to `0.5.0` worked for me.
