### ISSUE TITLE
Demo github-pages/preview.html reports "LinkError"

### ISSUE THREAD

**Issue by Lambdaris** [Myriad-Dreamin/typst.ts#614]
Save [preview.html](https://github.com/Myriad-Dreamin/typst.ts/blob/main/github-pages/preview.html) and open it locally but it does not work as expected (neither shows a real-time rendered svg nor exports pdf). 

Both _firefox 133.0_ and _edge 131.0.2903.86_ report `Uncaught (in promise) LinkError: import object field '__wbg_call_3bfa248576352471' is not a Function` in console. 

I guess something went wrong with loading wasm packages but can not figure it out.

**Comment by Myriad-Dreamin** [comment]
I have fixed it in https://github.com/Myriad-Dreamin/typst.ts/pull/623 and purged caches on jsdelivr. Now it works on my computer. Please invalid your browser caches and check it again.
