### ISSUE TITLE
typst-ts-node-compiler v0.5.3 is not released

### ISSUE THREAD

**Issue by Loosetooth** [Myriad-Dreamin/typst.ts#628]
When using pnpm to install the dependencies of a project using `rehype-typst@0.5.3` it complains that the 0.5.3 version of `typst-ts-node-compiler` is not found:
```
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @myriaddreamin/typst-ts-node-compiler@^0.5.3

This error happened while installing the dependencies of @myriaddreamin/rehype-typst@0.5.3

The latest release of @myriaddreamin/typst-ts-node-compiler is "0.5.2".
```

Can this package be released?

**Comment by Myriad-Dreamin** [comment]
Sorry, is was missed when releasing packages. let's fix the pipeline soon.

**Comment by Myriad-Dreamin** [comment]
Hey, I'm sorry if I did some bad thing, but I just confirmed that it had been released by GitHub CI. You were probably open it before the CI finished.

**Comment by Myriad-Dreamin** [comment]
This teaches us to respect release order (perhaps by some CI dependency). We should improve it ultimately.

**Comment by Loosetooth** [comment]
Thanks for the quick reply.
I was indeed too fast it seems like.
